# Generated by Django 5.2.5 on 2025-11-03 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Conversation', '0001_initial'),
        ('Message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'owner'), ('member', 'member')], default=None, max_length=30, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('delete_for_user_at', models.DateTimeField(blank=True, help_text='timestamp when user delete messages', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participants', to='Conversation.conversation')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by_participant', to='Message.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_participants',
                'indexes': [models.Index(fields=['conversation_id', 'user_id'], name='conversatio_convers_0398b8_idx')],
                'unique_together': {('conversation', 'user')},
            },
        ),
    ]
