# Generated by Django 5.2.5 on 2025-11-08 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0001_initial'),
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='Conversation.conversation'),
        ),
    ]
